### ISSUE TITLE
Add adaptor_kwargs to fixed point iteration?

### ISSUE THREAD

**Issue by ddundo** [pyroteus/goalie#98]
Hi! To tidy up my scripts, where I have many different versions of the adaptor functions, I found it useful to allow `adaptor_kwargs` to be passed to the `adaptor` function inside `MeshSeq.fixed_point_iteration`, similarly to how we can pass `solver_kwargs` now. Maybe it would be useful to add this?

**Comment by jwallwork23** [comment]
Sounds like a good idea. PR welcome!
